### PR TITLE
Update build, fix shading

### PR DESCRIPTION
**Pull request by jaredstehler**
previously naive shading was bundling jackson, et al on the raw package, causes conflict with other maven extensions using jackson (unshaded). 

this defensively shades the bundled deps to avoid any potential conflicts with other extension deps.

@jhaber

### CODE REVIEW

**Comment by jhaber** [comment]
Hmm do you know why we need shading at all? My past self is incredibly unhelpful 😭 
https://github.com/HubSpot/aws-maven/commit/64b4152c2a25f95f5103b02bb3d0adead6f8c630

**Comment by jaredstehler** [comment]
we could add the individual dependency jar files to `lib/ext`, i suppose?

**Comment by jhaber** [comment]
I wonder if we could register the extension in a different way. For example what if the Java buildpack created a `.mvn/extensions.xml`, seems like that would allow Maven to fetch transitive deps for us. All of the options seem to be documented here: https://maven.apache.org/guides/mini/guide-using-extensions.html
(the build extension pattern described at the end is enticing, but wouldn't allow us to build 3rd party code)

**Comment by jaredstehler** [comment]
I like that idea, and i think that's how we install the log segment extension. ill follow that path and see where it leads

**Comment by jaredstehler** [comment]
you still would want to defensively shade deps, unless we enforced standard deps for all extensions under `lib/ext` (i.e. a common parent pom for those extensions?)

**Comment by jaredstehler** [comment]
and the case where things like aws sdk bring in apache-http, which is provided under `./lib` (but could version drift)

**Comment by jhaber** [comment]
Are you sure we still need to shade? When using `.mvn/extensions.xml` I would expect the extension to run in its own classloader with whatever deps it wants, similar to how plugins can specify conflicting dependency versions and maven makes it "just work" (although I haven't actually tested this with extensions)

**Comment by jaredstehler** [comment]
> Are you sure we still need to shade? When using `.mvn/extensions.xml` I would expect the extension to run in its own classloader with whatever deps it wants, similar to how plugins can specify conflicting dependency versions and maven makes it "just work" (although I haven't actually tested this with extensions)

I will follow-up on this with some experimentation in a subsequent pr

**Pull request merged**
